### PR TITLE
fix: make changelist not be changed after peek

### LINKED ISSUE #41: dup code of 'peek-defintation' etc.
```patch
diff --git a/plugin/lsp.vim b/plugin/lsp.vim
index 561f14c..ff60759 100644
--- a/plugin/lsp.vim
+++ b/plugin/lsp.vim
@@ -24,25 +24,20 @@ if has('patch-8.2.4257')
   lspf.showServerCapabilities = lsp.ShowServerCapabilities
   lspf.setTraceServer = lsp.SetTraceServer
   lspf.gotoDefinition = lsp.GotoDefinition
   lspf.gotoDeclaration = lsp.GotoDeclaration
   lspf.gotoTypedef = lsp.GotoTypedef
   lspf.gotoImplementation = lsp.GotoImplementation
-  lspf.gotoDefinition = lsp.GotoDefinition
-  lspf.gotoDeclaration = lsp.GotoDeclaration
-  lspf.gotoTypedef = lsp.GotoTypedef
-  lspf.gotoImplementation = lsp.GotoImplementation
   lspf.showDiagnostics = lsp.ShowDiagnostics
   lspf.showCurrentDiag = lsp.LspShowCurrentDiag
   lspf.jumpToDiag = lsp.JumpToDiag
   lspf.jumpToDiag = lsp.JumpToDiag
   lspf.jumpToDiag = lsp.JumpToDiag
   lspf.diagHighlightEnable = lsp.DiagHighlightEnable
   lspf.diagHighlightDisable = lsp.DiagHighlightDisable
   lspf.showReferences = lsp.ShowReferences
-  lspf.showReferences = lsp.ShowReferences
   lspf.outline = lsp.Outline
   lspf.textDocFormat = lsp.TextDocFormat
   lspf.incomingCalls = lsp.IncomingCalls
   lspf.outgoingCalls = lsp.OutgoingCalls
   lspf.rename = lsp.Rename
   lspf.codeAction = lsp.CodeAction
@@ -70,25 +65,20 @@ elseif has('patch-8.2.4019')
   lspf.showServerCapabilities = lsp_import.ShowServerCapabilities
   lspf.setTraceServer = lsp_import.SetTraceServer
   lspf.gotoDefinition = lsp_import.GotoDefinition
   lspf.gotoDeclaration = lsp_import.GotoDeclaration
   lspf.gotoTypedef = lsp_import.GotoTypedef
   lspf.gotoImplementation = lsp_import.GotoImplementation
-  lspf.gotoDefinition = lsp_import.GotoDefinition
-  lspf.gotoDeclaration = lsp_import.GotoDeclaration
-  lspf.gotoTypedef = lsp_import.GotoTypedef
-  lspf.gotoImplementation = lsp_import.GotoImplementation
   lspf.showDiagnostics = lsp_import.ShowDiagnostics
   lspf.showCurrentDiag = lsp_import.LspShowCurrentDiag
   lspf.jumpToDiag = lsp_import.JumpToDiag
   lspf.jumpToDiag = lsp_import.JumpToDiag
   lspf.jumpToDiag = lsp_import.JumpToDiag
   lspf.diagHighlightEnable = lsp_import.DiagHighlightEnable
   lspf.diagHighlightDisable = lsp_import.DiagHighlightDisable
   lspf.showReferences = lsp_import.ShowReferences
-  lspf.showReferences = lsp_import.ShowReferences
   lspf.outline = lsp_import.Outline
   lspf.textDocFormat = lsp_import.TextDocFormat
   lspf.incomingCalls = lsp_import.IncomingCalls
   lspf.outgoingCalls = lsp_import.OutgoingCalls
   lspf.rename = lsp_import.Rename
   lspf.codeAction = lsp_import.CodeAction
@@ -148,25 +138,20 @@ else
   lspf.showServerCapabilities = ShowServerCapabilities
   lspf.setTraceServer = SetTraceServer
   lspf.gotoDefinition = GotoDefinition
   lspf.gotoDeclaration = GotoDeclaration
   lspf.gotoTypedef = GotoTypedef
   lspf.gotoImplementation = GotoImplementation
-  lspf.gotoDefinition = GotoDefinition
-  lspf.gotoDeclaration = GotoDeclaration
-  lspf.gotoTypedef = GotoTypedef
-  lspf.gotoImplementation = GotoImplementation
   lspf.showDiagnostics = ShowDiagnostics
   lspf.showCurrentDiag = LspShowCurrentDiag
   lspf.jumpToDiag = JumpToDiag
   lspf.jumpToDiag = JumpToDiag
   lspf.jumpToDiag = JumpToDiag
   lspf.diagHighlightEnable = DiagHighlightEnable
   lspf.diagHighlightDisable = DiagHighlightDisable
   lspf.showReferences = ShowReferences
-  lspf.showReferences = ShowReferences
   lspf.outline = Outline
   lspf.textDocFormat = TextDocFormat
   lspf.incomingCalls = IncomingCalls
   lspf.outgoingCalls = OutgoingCalls
   lspf.rename = Rename
   lspf.codeAction = CodeAction
```

### PR DESCRIPTION
**Pull request by Shane-XB-Qian**
closes #41

### CODE REVIEW

**Review by yegappan — COMMENTED** [review]
This PR still doesn't resolve the issue completely.  For example:

1. Open a file.
2. Run the LspPeekDefinition command to open a symbol in the preview window.
3. Press 'u'.

After the last step, the current buffer is marked as "changed".  This bug needs to be fixed in Vim.

**Comment by Shane-XB-Qian** [comment]
> After the last step, the current buffer is marked as "changed". 

// i cannot reproduce it, at my local seems had been workaround via this.


> This bug needs to be fixed in Vim.

// yes, i agree, but for now, let's just try to workaround it.. :-)

**Comment by Shane-XB-Qian** [comment]
> 1. Open a file.

how you open that file, was that just right after new vim instance just started, or it had been opened earlier? 
perhaps you've edit that file once..?

anyway, though this is a workaround, but it actually no harm anything, or actually perhaps better to re-use the same loaded buf vs but not pedit that fname again... :-)

**Comment by yegappan** [comment]
To avoid the problems with opening a preview window, I have committed a297e67103015dd592c2e6bc08d7dd01d4f9aac6 to use a popup window when peeking a symbol definition, declaration, etc.  Please try it out and let me know if you see any issues.

**Comment by Shane-XB-Qian** [comment]
though this (via popup instead pvw) can workaround this changelist issue too, 
but perhaps a bit different, since you can not copy something from a popup, or look into a bit more at a popup.
// but anyway, up to you, though someone probably would miss that peek in pvw feature.

**Comment by Shane-XB-Qian** [comment]
i like this popup peek anyway, by the way.
// but just user may like peek in pvw as well.

**Pull request closed without merging**
