### PR TITLE
Multiple server completion support

### PR DESCRIPTION
**Pull request by DanielViberg**
- Working mult server compl
- Removed time measure prop
- Tweaked LspResolver to be server id dependent
- Fixed text complete server dependent
- Reset tests

# Purpose: Volar 2 support

Note, should propbably be tested by more people before being merged to main!

## Config
```json
{
      "name": "vue-ls",
      "filetype": ["vue"],
      "path": "vue-language-server",
      "args": ["--stdio"],
      "features": {
        "definition": true,
        "rename": true
      },
      "initializationOptions": {
          "typescript": {
              "tsdk": "../node/v20.11.0/lib/node_modules/typescript/lib"
          }
      },
    },
    {
      "name": "ts-ls",
      "filetype": ["typescript", "javascript", "vue"],
      "path": "typescript-language-server",
      "args": ["--stdio"],
      "features": {
        "documentFormatting": false,
        "definition": true,
        "rename": true
      },
      "initializationOptions": {
          "plugins":[
            {
              "name": "@vue/typescript-plugin",
              "location":".../node/v20.11.0/lib/node_modules/@vue/typescript-plugin",
              "languages": ["vue"]
            }
          ]
      }
   }
```
## Status: 
- [x] completions
    - [x] auto imports
- [x] diagnostics
- [ ] definitions (working in some cases, but not all)
- [ ] references

### CODE REVIEW

**Comment by DanielViberg** [comment]
I noticed need for cleanup, will update soon.

**Comment by DanielViberg** [comment]
https://github.com/vuejs/language-tools/issues/3925#issuecomment-2011023845 Volar now does not need tsserver running in parallel. Parking this pr until future need.

**Comment by DanielViberg** [comment]
The above configuraion now works using https://github.com/DanielViberg/lsp/tree/dev-refactor. Only for completions, diag and rename so far. I have not validated all logic yet.

**Comment by briancarbone** [comment]
I'm surprised rename can done with multiple language servers. I quite liked the solution here which explicitly resolves which completion source should be used given the syntactical context: https://github.com/yegappan/lsp/pull/496. Ultimately, I _think_ only diagnostics and completions need "layering"; the obvious cases are `efm-langserver` or `@tailwindcss/language-server` underneath something else. Are there other LSP features that would benefit from a layered approach?

**Pull request closed without merging**
