### PR TITLE
Pr completion resolve item null

### PR DESCRIPTION
**Pull request by Shane-XB-Qian**
the reply.result of complete resolve perhaps is null.

### CODE REVIEW

**Comment by Shane-XB-Qian** [comment]
if i was not reading that lsp specification wrong, looks it said reply.result of complete resolve can be list, dict, and null.
now we only handle dict, that perhaps was a problem,
for now, i noticed perl lsp server displayed as `Lazy doc` but never really updated the info doc later.
for now, not sure if that was the cause.
// anyway, you may can refine it a bit later....

**Comment by yegappan** [comment]
According to the LSP specification https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem_resolve

the result of a complete resolve request is CompletionItem (a Dict).  This should
not be a List or null.  Need to see why the perl language server is returning 
some other type for the resolve request.

**Comment by yegappan** [comment]
I tried reproducing this issue with the Perl language server and couldn't reproduce the issue
when using the completion menu and the completion documentation is properly displayed.
Are you using the latest version of the plugin?

I am using the https://github.com/bscan/PerlNavigator Perl language server.  Which perl
language server are you using?

**Comment by Shane-XB-Qian** [comment]
it is `PLS` you can install it via cpan.
// https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion

--
shane.xb.qian

**Pull request merged**
