### PR TITLE
fix: some lsp server may include trigger char into compl item

### PR DESCRIPTION
**Pull request by Shane-XB-Qian**

### CODE REVIEW

**Comment by Shane-XB-Qian** [comment]
textedit.rang designed for multiple lines something, inserttext also, wish you can implement such logic into this lsp one day.
but so far I just wish it worked for most cases, specifically no outage err.

--
shane.xb.qian

**Comment by andlrc** [comment]
> textedit.rang designed for multiple lines something, inserttext also

`textEdit.range` is not, not for completion. See the relevant specification: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem

See 

> 	  * *Note:* The range of the edit must be a single line range and it must
>	  * contain the position at which completion has been requested.

**Comment by Shane-XB-Qian** [comment]
> If it's kept and the range isn't respected then this error appears:

> https://asciinema.org/a/054j5b7Vg0XlSQQRKfrwuhDld


have you ever tried this pr?
where you saw this err?
we did not such `rang` here, though maybe need concern this one day.
--
shane.xb.qian

**Comment by andlrc** [comment]
> have you ever tried this pr?

Yes

> where you saw this err?

The same errors as I linked above.

I recorded a video for you: https://asciinema.org/a/jW7zKNZRcnN6uLMSmRcNKaE9K

> we did not such `rang` here, though maybe need concern this one day.

Yes and that is a problem, because you NEED to respect the range if you want to use the value from `textEdit.newText`. Please take a look at the linked specifications.

**Comment by andlrc** [comment]
I also recorded this for you, which is using the php language server mentioned in #130 

https://asciinema.org/a/6lZVci3U1W2afZgwqkpxHXmwL

**Comment by Shane-XB-Qian** [comment]
have you recorded on correct commit base and branch?
why I saw it is omni compl?
or even it is, I cannot reproduce.

--
shane.xb.qian

**Comment by Shane-XB-Qian** [comment]
not sure if still worth, but to phpactor, @yegappan your searched suggestion looks was better one, so closing..

**Pull request closed without merging**
