### PR TITLE
fix(handlers): ignore `sqlLanguageServer.finishSetup`

### PR DESCRIPTION
**Pull request by maximyurevich**

### CODE REVIEW

**Comment by Shane-XB-Qian** [comment]
IMO not worth to add unsupported msg of less used lsp server into common main filter, you can add it via self-custom filter.
// have you seen comment at last similar PR?

--
shane.xb.qian

**Comment by maximyurevich** [comment]
> IMO not worth to add unsupported msg of less used lsp server into common main filter, you can add it via self-custom filter. // have you seen comment at last similar PR?
> […](#)
> -- shane.xb.qian

Why taplo, sqlls or eslint are less used?

**Comment by yegappan** [comment]
The LSP plugin should work without major issues with as many language servers as possible out of the box.   So I will merge this PR.

**Comment by Shane-XB-Qian** [comment]
so you plan to add all "you" think unsupported msg of various lsp servers like hard code like odd code into codebase?
that's the so-called "out of box"?

--
shane.xb.qian

**Pull request merged**
