### PR TITLE
none: tidy used item and trim tail spaces

### PR DESCRIPTION
**Pull request by Shane-XB-Qian**
- trim tail spaces
- pick up some to key

### CODE REVIEW

**Comment by Shane-XB-Qian** [comment]
> Why "abbr" and "dup" fields are removed from the key?

- had 'word' already,
- 'dup' maybe all same val.

-- 
shane.xb.qian

**Comment by yegappan** [comment]
> Why "abbr" and "dup" fields are removed from the key?
> - had 'word' already, - 'dup' maybe all same val.

it is better to keep `abbr` and `dup` to make sure there are no duplicates.
Note that a completion item may have `abbr` in addition to `word`.

**Comment by girishji** [comment]
Please do not remove `dup`. If LSP sends a snippet back and if the `abbr` or `word` matches a buffer word completion or vsnip completion, it will not show.

**Comment by Shane-XB-Qian** [comment]
> Please do not remove `dup`. 

remove where? if you meant in that compl items itself, then it should not and would not.

> If LSP sends a snippet back and if the `abbr` or `word` matches a buffer word completion or vsnip completion, it will not show.

are they same kind? was this really the problem?

**Pull request closed without merging**
